apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/currencyservice:2
        ports:
        - containerPort: 80

