apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: jenkins
spec:
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP